meu-site/
├── index.html
└── styles.css
# This is a basic workflow to help you get started with Actions

name: albert

#<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu Site Pessoal</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>

<header>
    <h1>Bem-vindo ao Meu Site!</h1>
</header>

<nav>
    <ul>
        <li><a href="#home">Início</a></li>
        <li><a href="#sobre">Sobre</a></li>
        <li><a href="#contato">Contato</a></li>
    </ul>
</nav>

<section id="home">
    <h2>Início</h2>
    <p>Esta é a página inicial do meu site. Aqui você pode encontrar informações sobre mim.</p>
</section>

<section id="sobre">
    <h2>Sobre</h2>
    <p>Sou um entusiasta da web e gosto de aprender sobre desenvolvimento web.</p>
</section>

<section id="contato">
    <h2>Contato</h2>
    <button id="show-form">Enviar Mensagem</button>
    <div id="contato-form" style="display: none;">
        <form id="form">
            <input type="text" placeholder="Seu Nome" required>
            <input type="email" placeholder="Seu E-mail" required>
            <textarea rows="4" placeholder="Sua Mensagem" required></textarea>
            <button type="submit">Enviar</button>
        </form>
    </div>
</section>

<footer>
    <p>&copy; 2024 Meu Site Pessoal. Todos os direitos reservados.</p>
</footer>

<script>
    document.getElementById('show-form').addEventListener('click', function() {
        const form = document.getElementById('contato-form');
        form.style.display = form.style.display === 'block' ? 'none' : 'block';
    });

    document.getElementById('form').addEventListener('submit', function(event) {
        event.preventDefault();
        alert('Mensagem enviada com sucesso!');
        this.reset();
        document.getElementById('contato-form').style.display = 'none';
    });
</script>

</body>
</html>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
    line-height: 1.6;
}

header {
    background: #007bff;
    color: #fff;
    padding: 20px 0;
    text-align: center;
}

nav {
    margin: 20px 0;
}

nav ul {
    list-style: none;
    padding: 0;
}

nav a {
    margin: 0 15px;
    color: #fff;
    text-decoration: none;
}

section {
    padding: 20px;
    margin: 10px;
    background: #fff;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

footer {
    text-align: center;
    padding: 20px 0;
    background: #007bff;
    color: #fff;
}

form input, form textarea {
    width: 100%;
    margin-bottom: 10px;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
}

form button {
    padding: 10px;
    background: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}

form button:hover {
    background: #0056b3;
}
 Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
